USE cram
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/changeMetadata.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/createScientist.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/deleteTimepoint.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/deleteVideo.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/getHeatshock.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/getRNAi.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/getSensor.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/getStrain.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/isAuthenticated.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/isLogged.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/login.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/loginf.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/myVids.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/rstudioAuths.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/simpleQuery.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/submitTPS.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/todoList.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/todoList2.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/todoList3.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/todoList4.sql
\. /Users/Doug/Projects/cram_db/mySQL/Scripts/todoListClean.sql
